version: '3.5'

services:
  query:
    image: ${REGISTRY}/statistics-query-elasticsearch:${VERSION}
    ports:
      - "8090:8080"
    configs:
      - source: utdata-api-properties
        target: /application.properties
    secrets:
      - source: utdata-api-elasticcloud-api-key-31122022
        target: utdata-api-elasticcloud-felles
    networks:
      net:
        aliases:
          - query
    deploy:
      mode: global
  ingest:
    image: ${REGISTRY}/statistics-ingest-elasticsearch:${VERSION}
    configs:
      - source: inndata-api-properties
        target: /application.properties
    secrets:
      - source: inndata-api-elasticcloud-api-key
        target: inndata-api-elasticcloud-felles
    ports:
      - "8091:8080"
    networks:
      net:
        aliases:
          - ingest
    deploy:
      mode: global

networks:
  net:
    driver: overlay
    attachable: true

# Can be random secret locally since using internal ElasticSearch in docker, but must exist otherwise startup of swarm fails.
secrets:
  inndata-api-elasticcloud-api-key:
    external: true
  utdata-api-elasticcloud-api-key-31122022:
    external: true

configs:
  inndata-api-properties:
    external: true
  utdata-api-properties:
    external: true
