version: '3.4'

services:
  query:
    image: difi/statistics-query-elasticsearch:${VERSION}
    ports:
      - "8080:8080"
    networks:
      - net
    deploy:
      mode: global
  ingest:
    image: difi/statistics-ingest-elasticsearch:${VERSION}
    ports:
      - "8081:8080"
    networks:
      - net
    deploy:
      mode: global
  authenticate:
    image: difi/statistics-authenticate:${VERSION}
    ports:
      - "8083:8080"
    networks:
      - net
    deploy:
      mode: global
  elasticsearch:
    image: difi/statistics-elasticsearch:${VERSION}
    ports:
      - "8082:9200"
    command: -Ediscovery.zen.ping.unicast.hosts=elasticsearch_gossip:9301 -Enode.master=false
    stop_grace_period: 5m
    volumes:
      - statistics-data:/usr/share/elasticsearch/data
    networks:
      - net
    deploy:
      mode: global
  elasticsearch_gossip:
    image: difi/statistics-elasticsearch:${VERSION}
    ports:
      - "9201:9200"
    command: -Etransport.tcp.port=9301 -Enode.data=false
    stop_grace_period: 5m
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1

networks:
  net:
    driver: overlay
    attachable: true

volumes:
  statistics-data:
    external: true
