version: '3.4'

services:
  query:
    image: ${REGISTRY}/statistics-query-elasticsearch:${VERSION}
    hostname: query
    ports:
      - "8080:8080"
    networks:
      net:
        aliases:
          - query
    deploy:
      mode: global
  ingest:
    image: ${REGISTRY}/statistics-ingest-elasticsearch:${VERSION}
    hostname: ingest
    ports:
      - "8081:8080"
    networks:
      net:
        aliases:
          - ingest
    deploy:
      mode: global
  authenticate:
    image: ${REGISTRY}/statistics-authenticate:${VERSION}
    ports:
      - "8083:8080"
    networks:
      - net
    deploy:
      mode: global
  elasticsearch:
    image: ${REGISTRY}/statistics-elasticsearch:${VERSION}
    ports:
      - "8082:9200"
    stop_grace_period: 5m
    command: bin/elasticsearch
    environment:
      - discovery.zen.ping.unicast.hosts=elasticsearch_gossip:9301
      - node.master=false
      - bootstrap.memory_lock=true
    volumes:
      - statistics-data:/usr/share/elasticsearch/data
    networks:
      - net
    deploy:
      mode: global
  elasticsearch_gossip:
    image: ${REGISTRY}/statistics-elasticsearch:${VERSION}
    ports:
      - "9201:9200"
    stop_grace_period: 5m
    command: bin/elasticsearch -Etransport.tcp.port=9301
    environment:
      - node.data=false
      - bootstrap.memory_lock=true
    networks:
      net:
    deploy:
      mode: replicated
      replicas: 1

networks:
  net:
    driver: overlay
    attachable: true

volumes:
  statistics-data:
    external: true
